name: ESLint

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]
  schedule:
    - cron: "21 23 * * 1"

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Lint
        run: pnpm run lint
